### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VitrolicWither** [Lawlzee/ScrappyChests#1]
Awesome mod would be cool if it was an artifact so you could toggle it on and off mid game.

**Comment by Lawlzee** [comment]
Hi, thanks for the feedback. You can enable or disable the mod at any point in the settings (`Settings > Mod Options > ScrappyChests > Configuration > Mod enabled`). This should even work in the middle of a run.

I don't want to make the mod an artifact, because it would make harder to play the mod on eclipse. You would need a mod to enable artifacts in eclipse.

**Comment by VitrolicWither** [comment]
Oh okay I didn't know you could do that in the mod options and that makes sense. Thank you for responding
